### ISSUE TITLE
Snake case objects properties

### ISSUE THREAD

**Issue by beschoenen** [MapCreatorEU/m4n-api#48]
Object properties are camel cased when they're loaded from the API, but when you try to save something it's not changed back.

**Comment by Mechazawa** [comment]
Can you give me an example of the request?

**Comment by beschoenen** [comment]
In the studio, we only want to use for instance `languageCode` in the models, not `language_code`. The wrapper should automatically reformat this.

I know it's working for update requests, but not for new objects, so:

`api.users.new(data).save().then(console.log)`

**Comment by Mechazawa** [comment]
Does the branch [fix/normalize_keys](https://github.com/MapCreatorEU/m4n-api/tree/fix/normalize_keys) fix the issue?
