### ISSUE TITLE
Create statefull PaginatedResourceWrapper 

### ISSUE THREAD

**Issue by Mechazawa** [MapCreatorEU/m4n-api#53]
Should use a proper cache and allow for anything normally available but use an aggregate dataset.

Should be accessable through `api.resource.toListing()` or something.

**Comment by beschoenen** [comment]
defaults for the cache could be:

```
disableCache: Boolean = false
cacheExpiresIn: Number = 30
```

**Comment by Mechazawa** [comment]
What would be the best name for the class? `PaginatedResourceWrapper`?

**Comment by beschoenen** [comment]
That's sounds good.
