### ISSUE TITLE
Change _listResource into a resourceproxy where applicable

### ISSUE THREAD

**Issue by Mechazawa** [MapCreatorEU/m4n-api#65]
This means that stuff like this will be possible:

```js
api.jobs.select(1).results.select(3).archiveUrl();
```

**Comment by beschoenen** [comment]
```js
window.api.jobs.select(job.job_id).revisions.select(job.revision).result.preview.download().then(image => {
    job.image = image
})
```

**Comment by Mechazawa** [comment]
@beschoenen I'd assume this is only for multi-key urls?

**Comment by beschoenen** [comment]
This should work for everything

**Comment by Mechazawa** [comment]
I'll make a first revision for review so that you can sign-off on the structure.

**Comment by Mechazawa** [comment]
Something like `/v1/organisation/{id}/colors` won't be very useful to proxy. This is because `api.organisations.select('mine').colors()` already returns a resource listing promise. Unless this is something that is desired as well.

**Comment by Mechazawa** [comment]
With that I mean that only multi-key routes should get treatment.

**Comment by beschoenen** [comment]
I should be able to filter the colors in your example. So, call `limit` or `select`.

**Comment by Mechazawa** [comment]
So `.colors` should return a proxy without the `.select` and `.get` methods? Because those will be unavailable. I can make it that they are not available when the route is already pre-formatted. Such as `/v1/organisation/123/colors`.

**Comment by beschoenen** [comment]
Maybe those should be a new object, something like `OwnableResourceProxy`

**Comment by Mechazawa** [comment]
I'll think about it. For now I'll be invetigating the way `resourceName` and `resourcePath` are tied into the application. I want to be able to overwrite the resourcePath for "deep" proxies.
