### ISSUE TITLE
Upload and download to S3 buckets

### ISSUE THREAD

**Issue by akashmapcreator** [MapCreatorEU/m4n-api#80]
The goal is to have an API to intermediate the actions between the google Docs and the S3 buckets. Please look at the following code to better understand the goal of this issue.

`function uploadJson( ) {
        require_once 'S3Uploader.php';
        $file_path = $_POST['path'];
        $s3 = new S3Uploader('m4n-focus', 'Maps4News');
        // Retrieve coordinates
        $json = $this->getGeojson();
        $s3->uploadJson( $file_path, $json );
        return true; // Make decent return message
    }
    function getGeojson( ) {        
        $job = $this->getJobObject();
        $geojson = new Job2Geojson( $job );
        return $geojson->toString();
    }`

See the file below to understand how to push data into an S3 bucket through php
[s3uploader.txt](https://github.com/MapCreatorEU/m4n-api/files/1430784/s3uploader.txt)

**Comment by Mechazawa** [comment]
Moved to https://github.com/MapCreatorEU/api/issues/406
